EvclidClang:
	gcc -o2  Evclid.c -o EvklidClanguage
EvclidRust:
	rustc Evclid.rf  -o EvclidRust

run-gcc: EvclidClang
	./EvklidClanguage
run-golang:
	go run Evclid.go
run-lua:
	lua5.3 Evclid.lua
run-rust:EvclidRust
	./EvclidRust
run-java:
	java Evclid.java
run-python3:
	python3 Evclid.py
