build:
	gcc -o2  Evclid.c -o EvklidClanguage
	rustc Evclid.rf  -o EvclidRust

CLanguageRun:
	./Evklid
GoRun:
	go run Evclid.go
LuaRun:
	lua5.3 Evclid.lua
PyRun:
	python3 Evklid.py
RustRun:
	./EvclidRust
