ErastofenCpp:
	g++  Erastofen.cpp -o ErastofenCpp

ErastofenClanguage:
	gcc -o2 Erastofen.c -o ErastofenClanguage

run-gcc: ErastofenClanguage
	./ErastofenClanguage

run-cpp: ErastofenCpp
	./ErastofenClanguage

run-python3:
	python3 Eratosfen.py
